#!/usr/bin/env python
"""
Turn uploads/logo.png into a small inlined asset the app can use everywhere.

The source is 1920x1621 and ~900 KB. It is displayed at 56 px. Shipping the
original would be the single heaviest thing on the page by a wide margin, to
people who are often on a 3G phone at a health post — so it is resized here and
committed as a generated stylesheet.

Why a data URI in CSS rather than an <img src="logo.png">:
the app is served two ways (see docs/HOSTING.md). Vercel can serve a .png
happily; Apps Script's HtmlService cannot serve a binary file at all. A data URI
in the stylesheet is the one form that works identically on both, from a single
source, with no second copy to drift.

    python scripts/make-logo.py

Writes public/logo.css. Re-run only if uploads/logo.png changes.
"""
import base64
import io
import os
import sys

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "uploads", "logo.png")
OUT = os.path.join(ROOT, "public", "logo.css")

# Displayed at 56 px; 128 covers a 2x display with room to spare. Going larger
# costs bytes on every page load and buys nothing anyone can see.
MAX_EDGE = 128

if not os.path.exists(SRC):
    sys.exit("missing " + SRC)

img = Image.open(SRC)
img = img.convert("RGBA")
before = os.path.getsize(SRC)

img.thumbnail((MAX_EDGE, MAX_EDGE), Image.LANCZOS)

# Quantising to a 256-colour palette takes this from ~27 KB to ~7 KB. An emblem
# is flat colour and line work, so at the size it is actually drawn there is
# nothing in the difference anyone can see. FASTOCTREE is used because it keeps
# the alpha channel, which the default method does not.
paletted = img.quantize(colors=256, method=Image.FASTOCTREE)

buf = io.BytesIO()
paletted.save(buf, format="PNG", optimize=True)
data = buf.getvalue()

b64 = base64.b64encode(data).decode("ascii")

css = """/* GENERATED by scripts/make-logo.py from uploads/logo.png — do not edit.
   The emblem, resized to %(w)dx%(h)d and inlined as a data URI so that both the
   Vercel build and the Apps Script /exec build can show it. HtmlService cannot
   serve a binary file, which is why this is CSS and not an <img src>. */
.emblem {
  background-image: url("data:image/png;base64,%(b64)s");
  background-size: contain;
  background-repeat: no-repeat;
  background-position: center;
  display: inline-block;
  flex: 0 0 auto;
}
""" % {"w": img.width, "h": img.height, "b64": b64}

with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(css)

print("source     %6.1f KB  (%dx%d)" % (before / 1024.0, Image.open(SRC).width,
                                        Image.open(SRC).height))
print("resized    %6.1f KB  (%dx%d)" % (len(data) / 1024.0, img.width, img.height))
print("logo.css   %6.1f KB  (base64 inflates by ~4/3)" % (len(css) / 1024.0,))
